server:
  port: 8088
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/balloon_blog
    username: handsome
    password: handsome
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      use-global-data-source-stat: true
      filter:
        stat:
          merge-sql: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations:
    - classpath: mapper/*.xml
    - classpath: com/**/mapper/*.xml