package com.handsome.balloonblog.mbg.mapper;

import com.handsome.balloonblog.mbg.model.TArticles;
import com.handsome.balloonblog.mbg.model.TArticlesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    long countByExample(TArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int deleteByExample(TArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int deleteByPrimaryKey(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int insert(TArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int insertSelective(TArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    List<TArticles> selectByExampleWithBLOBs(TArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    List<TArticles> selectByExample(TArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    TArticles selectByPrimaryKey(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") TArticles record, @Param("example") TArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TArticles record, @Param("example") TArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExample(@Param("record") TArticles record, @Param("example") TArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKeySelective(TArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKey(TArticles record);
}