package com.handsome.balloonblog.mbg.mapper;

import com.handsome.balloonblog.mbg.model.TArticleLabel;
import com.handsome.balloonblog.mbg.model.TArticleLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TArticleLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    long countByExample(TArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int deleteByExample(TArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int deleteByPrimaryKey(@Param("articleId") Long articleId, @Param("labelId") Long labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int insert(TArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int insertSelective(TArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    List<TArticleLabel> selectByExample(TArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    TArticleLabel selectByPrimaryKey(@Param("articleId") Long articleId, @Param("labelId") Long labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") TArticleLabel record, @Param("example") TArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExample(@Param("record") TArticleLabel record, @Param("example") TArticleLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKeySelective(TArticleLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKey(TArticleLabel record);
}