package com.handsome.balloonblog.mbg.mapper;

import com.handsome.balloonblog.mbg.model.TComments;
import com.handsome.balloonblog.mbg.model.TCommentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    long countByExample(TCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int deleteByExample(TCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int deleteByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int insert(TComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int insertSelective(TComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    List<TComments> selectByExampleWithBLOBs(TCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    List<TComments> selectByExample(TCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    TComments selectByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") TComments record, @Param("example") TCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TComments record, @Param("example") TCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExample(@Param("record") TComments record, @Param("example") TCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKeySelective(TComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKey(TComments record);
}