package com.handsome.balloonblog.mbg.mapper;

import com.handsome.balloonblog.mbg.model.TLabels;
import com.handsome.balloonblog.mbg.model.TLabelsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLabelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    long countByExample(TLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int deleteByExample(TLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int deleteByPrimaryKey(Long labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int insert(TLabels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int insertSelective(TLabels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    List<TLabels> selectByExampleWithBLOBs(TLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    List<TLabels> selectByExample(TLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    TLabels selectByPrimaryKey(Long labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") TLabels record, @Param("example") TLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TLabels record, @Param("example") TLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByExample(@Param("record") TLabels record, @Param("example") TLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKeySelective(TLabels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TLabels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    int updateByPrimaryKey(TLabels record);
}