package com.handsome.balloonblog.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TArticleLabel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_label.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_label.label_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_label.article_label_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date articleLabelGmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_label.article_label_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date articleLabelGmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_label.article_id
     *
     * @return the value of t_article_label.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_label.article_id
     *
     * @param articleId the value for t_article_label.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_label.label_id
     *
     * @return the value of t_article_label.label_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_label.label_id
     *
     * @param labelId the value for t_article_label.label_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_label.article_label_gmt_create
     *
     * @return the value of t_article_label.article_label_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getArticleLabelGmtCreate() {
        return articleLabelGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_label.article_label_gmt_create
     *
     * @param articleLabelGmtCreate the value for t_article_label.article_label_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleLabelGmtCreate(Date articleLabelGmtCreate) {
        this.articleLabelGmtCreate = articleLabelGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_label.article_label_gmt_modified
     *
     * @return the value of t_article_label.article_label_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getArticleLabelGmtModified() {
        return articleLabelGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_label.article_label_gmt_modified
     *
     * @param articleLabelGmtModified the value for t_article_label.article_label_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleLabelGmtModified(Date articleLabelGmtModified) {
        this.articleLabelGmtModified = articleLabelGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_label
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", labelId=").append(labelId);
        sb.append(", articleLabelGmtCreate=").append(articleLabelGmtCreate);
        sb.append(", articleLabelGmtModified=").append(articleLabelGmtModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}