package com.handsome.balloonblog.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TArticles implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_views
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long articleViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_comment_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long articleCommentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_like_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long articleLikeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date articleGmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date articleGmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_title
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_articles.article_content
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String articleContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_id
     *
     * @return the value of t_articles.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_id
     *
     * @param articleId the value for t_articles.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.user_id
     *
     * @return the value of t_articles.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.user_id
     *
     * @param userId the value for t_articles.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_views
     *
     * @return the value of t_articles.article_views
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getArticleViews() {
        return articleViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_views
     *
     * @param articleViews the value for t_articles.article_views
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleViews(Long articleViews) {
        this.articleViews = articleViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_comment_count
     *
     * @return the value of t_articles.article_comment_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getArticleCommentCount() {
        return articleCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_comment_count
     *
     * @param articleCommentCount the value for t_articles.article_comment_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleCommentCount(Long articleCommentCount) {
        this.articleCommentCount = articleCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_like_count
     *
     * @return the value of t_articles.article_like_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getArticleLikeCount() {
        return articleLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_like_count
     *
     * @param articleLikeCount the value for t_articles.article_like_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleLikeCount(Long articleLikeCount) {
        this.articleLikeCount = articleLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_gmt_create
     *
     * @return the value of t_articles.article_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getArticleGmtCreate() {
        return articleGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_gmt_create
     *
     * @param articleGmtCreate the value for t_articles.article_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleGmtCreate(Date articleGmtCreate) {
        this.articleGmtCreate = articleGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_gmt_modified
     *
     * @return the value of t_articles.article_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getArticleGmtModified() {
        return articleGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_gmt_modified
     *
     * @param articleGmtModified the value for t_articles.article_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleGmtModified(Date articleGmtModified) {
        this.articleGmtModified = articleGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_title
     *
     * @return the value of t_articles.article_title
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_title
     *
     * @param articleTitle the value for t_articles.article_title
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_articles.article_content
     *
     * @return the value of t_articles.article_content
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_articles.article_content
     *
     * @param articleContent the value for t_articles.article_content
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_articles
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleId=").append(articleId);
        sb.append(", userId=").append(userId);
        sb.append(", articleViews=").append(articleViews);
        sb.append(", articleCommentCount=").append(articleCommentCount);
        sb.append(", articleLikeCount=").append(articleLikeCount);
        sb.append(", articleGmtCreate=").append(articleGmtCreate);
        sb.append(", articleGmtModified=").append(articleGmtModified);
        sb.append(", articleTitle=").append(articleTitle);
        sb.append(", articleContent=").append(articleContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}