package com.handsome.balloonblog.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TComments implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.comment_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.comment_like_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long commentLikeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.parent_comment_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long parentCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.comment_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date commentGmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.comment_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date commentGmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.comment_content
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.comment_id
     *
     * @return the value of t_comments.comment_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.comment_id
     *
     * @param commentId the value for t_comments.comment_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.user_id
     *
     * @return the value of t_comments.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.user_id
     *
     * @param userId the value for t_comments.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.article_id
     *
     * @return the value of t_comments.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.article_id
     *
     * @param articleId the value for t_comments.article_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.comment_like_count
     *
     * @return the value of t_comments.comment_like_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getCommentLikeCount() {
        return commentLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.comment_like_count
     *
     * @param commentLikeCount the value for t_comments.comment_like_count
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setCommentLikeCount(Long commentLikeCount) {
        this.commentLikeCount = commentLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.parent_comment_id
     *
     * @return the value of t_comments.parent_comment_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getParentCommentId() {
        return parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.parent_comment_id
     *
     * @param parentCommentId the value for t_comments.parent_comment_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setParentCommentId(Long parentCommentId) {
        this.parentCommentId = parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.comment_gmt_create
     *
     * @return the value of t_comments.comment_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getCommentGmtCreate() {
        return commentGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.comment_gmt_create
     *
     * @param commentGmtCreate the value for t_comments.comment_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setCommentGmtCreate(Date commentGmtCreate) {
        this.commentGmtCreate = commentGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.comment_gmt_modified
     *
     * @return the value of t_comments.comment_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getCommentGmtModified() {
        return commentGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.comment_gmt_modified
     *
     * @param commentGmtModified the value for t_comments.comment_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setCommentGmtModified(Date commentGmtModified) {
        this.commentGmtModified = commentGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comments.comment_content
     *
     * @return the value of t_comments.comment_content
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comments.comment_content
     *
     * @param commentContent the value for t_comments.comment_content
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comments
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", userId=").append(userId);
        sb.append(", articleId=").append(articleId);
        sb.append(", commentLikeCount=").append(commentLikeCount);
        sb.append(", parentCommentId=").append(parentCommentId);
        sb.append(", commentGmtCreate=").append(commentGmtCreate);
        sb.append(", commentGmtModified=").append(commentGmtModified);
        sb.append(", commentContent=").append(commentContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}