package com.handsome.balloonblog.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TLabels implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_labels.label_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long labelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_labels.label_name
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_labels.label_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date labelGmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_labels.label_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date labelGmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_labels.label_description
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String labelDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_labels.label_id
     *
     * @return the value of t_labels.label_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_labels.label_id
     *
     * @param labelId the value for t_labels.label_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_labels.label_name
     *
     * @return the value of t_labels.label_name
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_labels.label_name
     *
     * @param labelName the value for t_labels.label_name
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_labels.label_gmt_create
     *
     * @return the value of t_labels.label_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getLabelGmtCreate() {
        return labelGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_labels.label_gmt_create
     *
     * @param labelGmtCreate the value for t_labels.label_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setLabelGmtCreate(Date labelGmtCreate) {
        this.labelGmtCreate = labelGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_labels.label_gmt_modified
     *
     * @return the value of t_labels.label_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getLabelGmtModified() {
        return labelGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_labels.label_gmt_modified
     *
     * @param labelGmtModified the value for t_labels.label_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setLabelGmtModified(Date labelGmtModified) {
        this.labelGmtModified = labelGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_labels.label_description
     *
     * @return the value of t_labels.label_description
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getLabelDescription() {
        return labelDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_labels.label_description
     *
     * @param labelDescription the value for t_labels.label_description
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setLabelDescription(String labelDescription) {
        this.labelDescription = labelDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_labels
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", labelId=").append(labelId);
        sb.append(", labelName=").append(labelName);
        sb.append(", labelGmtCreate=").append(labelGmtCreate);
        sb.append(", labelGmtModified=").append(labelGmtModified);
        sb.append(", labelDescription=").append(labelDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}