package com.handsome.balloonblog.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_open_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String userOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_nickname
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_sex
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Byte userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_province
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String userProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_country
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String userCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_headimgurl
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String userHeadimgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_email
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_email_status
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Byte userEmailStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_last_ip
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private String userLastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_last_login_time
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date userLastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date userGmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private Date userGmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_open_id
     *
     * @return the value of t_user.user_open_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getUserOpenId() {
        return userOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_open_id
     *
     * @param userOpenId the value for t_user.user_open_id
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserOpenId(String userOpenId) {
        this.userOpenId = userOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_nickname
     *
     * @return the value of t_user.user_nickname
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_nickname
     *
     * @param userNickname the value for t_user.user_nickname
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_sex
     *
     * @return the value of t_user.user_sex
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Byte getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_sex
     *
     * @param userSex the value for t_user.user_sex
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserSex(Byte userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_province
     *
     * @return the value of t_user.user_province
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getUserProvince() {
        return userProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_province
     *
     * @param userProvince the value for t_user.user_province
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserProvince(String userProvince) {
        this.userProvince = userProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_country
     *
     * @return the value of t_user.user_country
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getUserCountry() {
        return userCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_country
     *
     * @param userCountry the value for t_user.user_country
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserCountry(String userCountry) {
        this.userCountry = userCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_headimgurl
     *
     * @return the value of t_user.user_headimgurl
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getUserHeadimgurl() {
        return userHeadimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_headimgurl
     *
     * @param userHeadimgurl the value for t_user.user_headimgurl
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserHeadimgurl(String userHeadimgurl) {
        this.userHeadimgurl = userHeadimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_email
     *
     * @return the value of t_user.user_email
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_email
     *
     * @param userEmail the value for t_user.user_email
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_email_status
     *
     * @return the value of t_user.user_email_status
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Byte getUserEmailStatus() {
        return userEmailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_email_status
     *
     * @param userEmailStatus the value for t_user.user_email_status
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserEmailStatus(Byte userEmailStatus) {
        this.userEmailStatus = userEmailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_last_ip
     *
     * @return the value of t_user.user_last_ip
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public String getUserLastIp() {
        return userLastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_last_ip
     *
     * @param userLastIp the value for t_user.user_last_ip
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserLastIp(String userLastIp) {
        this.userLastIp = userLastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_last_login_time
     *
     * @return the value of t_user.user_last_login_time
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getUserLastLoginTime() {
        return userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_last_login_time
     *
     * @param userLastLoginTime the value for t_user.user_last_login_time
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserLastLoginTime(Date userLastLoginTime) {
        this.userLastLoginTime = userLastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_gmt_create
     *
     * @return the value of t_user.user_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getUserGmtCreate() {
        return userGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_gmt_create
     *
     * @param userGmtCreate the value for t_user.user_gmt_create
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserGmtCreate(Date userGmtCreate) {
        this.userGmtCreate = userGmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_gmt_modified
     *
     * @return the value of t_user.user_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public Date getUserGmtModified() {
        return userGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_gmt_modified
     *
     * @param userGmtModified the value for t_user.user_gmt_modified
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    public void setUserGmtModified(Date userGmtModified) {
        this.userGmtModified = userGmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Wed Aug 05 19:30:20 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userOpenId=").append(userOpenId);
        sb.append(", userNickname=").append(userNickname);
        sb.append(", userSex=").append(userSex);
        sb.append(", userProvince=").append(userProvince);
        sb.append(", userCountry=").append(userCountry);
        sb.append(", userHeadimgurl=").append(userHeadimgurl);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userEmailStatus=").append(userEmailStatus);
        sb.append(", userLastIp=").append(userLastIp);
        sb.append(", userLastLoginTime=").append(userLastLoginTime);
        sb.append(", userGmtCreate=").append(userGmtCreate);
        sb.append(", userGmtModified=").append(userGmtModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}